linters:
  disable-all: true
  enable:
    - gci
    - gofmt
    - goimports
    - govet
    - ineffassign
    - staticcheck
    - unused

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/delaneyj/witchbolt)
  goimports:
    local-prefixes: github.com/delaneyj/witchbolt
  staticcheck:
    checks:
      - all
      - -QF1003
      - -QF1010
      - -ST1003
      - -ST1005
      - -ST1012

issues:
  max-same-issues: 0
